name: Build

on:
  workflow_call:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
          fetch-depth: 1
      - name: Create Patch
        run: |
          bin/ParanormasightChsLocalizationHelper
          compress-archive out/patch/* out/patch-text.zip -force
      - name: Upload patch
        uses: actions/upload-artifact@v3
        with:
          name: patch
          path: |
            out/patch/*
      - run: tail -n +2 README.md > NEW_README.md
      - name: GitHub Release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: "out/patch-text.zip"
          bodyFile: NEW_README.md
          name: "《灵异视界 FILE23 本所七大不可思议》文本翻译汉化"
          tag: publish
          token: ${{ secrets.GITHUB_TOKEN }}